[functions]
directory = "src"

[build]
publish = "client/build"

[[redirects]]
from = "/group1"
to = "/.netlify/functions/api/group1"

[[redirects]]
from = "/group2"
to = "/.netlify/functions/api/group2"
